# Generated by Django 5.0.4 on 2024-04-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_university_short_name_university_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
